name: pytorch-yolov3-helloworld
channels:
  - defaults
dependencies:
  - python=3.7.9
  - pip=21.2.2
  - pip:
      - numpy==1.19.5
      - torch>=1.8.1
      - torchvision>=0.8.2
      - matplotlib==3.3.3
      - tensorboard==2.4.0
      - terminaltables==3.1.0
      - Pillow==8.1.0
      - tqdm==4.55.1
      - imgaug==0.4.0
      - torchsummary==1.5.1
